const STARTER_HSN_SAC_MASTER = [
  {
    code: "9988",
    description: "Manufacturing services on physical inputs owned by others",
    suggested_gst_rate: 5.0,
    entry_type: "JOBWORK",
    chapter: "SAC 9988",
    keywords: "job work processing stitching dyeing printing finishing contract manufacturing",
    is_active: 1,
  },
  {
    code: "9954",
    description: "Construction services",
    suggested_gst_rate: 18.0,
    entry_type: "SERVICE",
    chapter: "SAC 9954",
    keywords: "construction civil contractor building work",
    is_active: 1,
  },
  {
    code: "9983",
    description: "Other professional, technical and business services",
    suggested_gst_rate: 18.0,
    entry_type: "SERVICE",
    chapter: "SAC 9983",
    keywords: "consulting professional technical business advisory",
    is_active: 1,
  },
  {
    code: "998313",
    description: "Information technology consulting and support services",
    suggested_gst_rate: 18.0,
    entry_type: "SERVICE",
    chapter: "SAC 9983",
    keywords: "software development it consulting implementation support",
    is_active: 1,
  },
  {
    code: "998314",
    description: "IT design and development services",
    suggested_gst_rate: 18.0,
    entry_type: "SERVICE",
    chapter: "SAC 9983",
    keywords: "software app website development programming coding",
    is_active: 1,
  },
  {
    code: "996511",
    description: "Road transport services of goods",
    suggested_gst_rate: 5.0,
    entry_type: "SERVICE",
    chapter: "SAC 9965",
    keywords: "transport freight logistics trucking delivery",
    is_active: 1,
  },
  {
    code: "996601",
    description: "Rental services of transport vehicles",
    suggested_gst_rate: 18.0,
    entry_type: "SERVICE",
    chapter: "SAC 9966",
    keywords: "vehicle rental transport hire",
    is_active: 1,
  },
  {
    code: "997212",
    description: "Accounting and bookkeeping services",
    suggested_gst_rate: 18.0,
    entry_type: "SERVICE",
    chapter: "SAC 9972",
    keywords: "accounting bookkeeping gst filing audit",
    is_active: 1,
  },
  {
    code: "997331",
    description: "Licensing services for software and databases",
    suggested_gst_rate: 18.0,
    entry_type: "SERVICE",
    chapter: "SAC 9973",
    keywords: "software license saas subscription",
    is_active: 1,
  },
  {
    code: "999293",
    description: "Laundry, cleaning and dyeing services",
    suggested_gst_rate: 18.0,
    entry_type: "SERVICE",
    chapter: "SAC 9992",
    keywords: "laundry dry clean dyeing cleaning",
    is_active: 1,
  },
  {
    code: "1001",
    description: "Wheat and meslin",
    suggested_gst_rate: 0.0,
    entry_type: "GOODS",
    chapter: "Chapter 10",
    keywords: "wheat grain cereal",
    is_active: 1,
  },
  {
    code: "1701",
    description: "Cane or beet sugar and chemically pure sucrose",
    suggested_gst_rate: 5.0,
    entry_type: "GOODS",
    chapter: "Chapter 17",
    keywords: "sugar sweetener",
    is_active: 1,
  },
  {
    code: "2402",
    description: "Cigars, cheroots, cigarillos and cigarettes",
    suggested_gst_rate: 28.0,
    entry_type: "GOODS",
    chapter: "Chapter 24",
    keywords: "cigarette tobacco smoking",
    is_active: 1,
  },
  {
    code: "3004",
    description: "Medicaments for therapeutic or prophylactic uses",
    suggested_gst_rate: 12.0,
    entry_type: "GOODS",
    chapter: "Chapter 30",
    keywords: "medicine pharma tablet syrup drug",
    is_active: 1,
  },
  {
    code: "3304",
    description: "Beauty or make-up preparations and skin care",
    suggested_gst_rate: 18.0,
    entry_type: "GOODS",
    chapter: "Chapter 33",
    keywords: "cosmetics beauty makeup skincare",
    is_active: 1,
  },
  {
    code: "3901",
    description: "Polymers of ethylene in primary forms",
    suggested_gst_rate: 18.0,
    entry_type: "GOODS",
    chapter: "Chapter 39",
    keywords: "plastic polymer granules resin",
    is_active: 1,
  },
  {
    code: "4411",
    description: "Fibreboard of wood or other ligneous materials",
    suggested_gst_rate: 18.0,
    entry_type: "GOODS",
    chapter: "Chapter 44",
    keywords: "board mdf plywood fibre wood",
    is_active: 1,
  },
  {
    code: "4819",
    description: "Cartons, boxes and packing containers of paper",
    suggested_gst_rate: 12.0,
    entry_type: "GOODS",
    chapter: "Chapter 48",
    keywords: "paper box carton packaging corrugated",
    is_active: 1,
  },
  {
    code: "5208",
    description: "Woven fabrics of cotton",
    suggested_gst_rate: 5.0,
    entry_type: "GOODS",
    chapter: "Chapter 52",
    keywords: "cotton fabric textile cloth",
    is_active: 1,
  },
  {
    code: "6109",
    description: "T-shirts, singlets and other vests, knitted or crocheted",
    suggested_gst_rate: 5.0,
    entry_type: "GOODS",
    chapter: "Chapter 61",
    keywords: "tshirt t-shirt vest knitwear garment apparel",
    is_active: 1,
  },
  {
    code: "6203",
    description: "Mens or boys suits, ensembles, jackets and trousers",
    suggested_gst_rate: 12.0,
    entry_type: "GOODS",
    chapter: "Chapter 62",
    keywords: "mens garments trousers jackets apparel",
    is_active: 1,
  },
  {
    code: "6403",
    description: "Footwear with outer soles of rubber, plastics or leather",
    suggested_gst_rate: 18.0,
    entry_type: "GOODS",
    chapter: "Chapter 64",
    keywords: "shoes footwear sandals",
    is_active: 1,
  },
  {
    code: "7308",
    description: "Structures and parts of structures, of iron or steel",
    suggested_gst_rate: 18.0,
    entry_type: "GOODS",
    chapter: "Chapter 73",
    keywords: "steel structure fabrication beam frame",
    is_active: 1,
  },
  {
    code: "8471",
    description: "Automatic data processing machines and units thereof",
    suggested_gst_rate: 18.0,
    entry_type: "GOODS",
    chapter: "Chapter 84",
    keywords: "computer laptop cpu server hardware",
    is_active: 1,
  },
  {
    code: "8504",
    description: "Electrical transformers, static converters and inductors",
    suggested_gst_rate: 18.0,
    entry_type: "GOODS",
    chapter: "Chapter 85",
    keywords: "transformer inverter charger electrical",
    is_active: 1,
  },
  {
    code: "8517",
    description: "Telephone sets, smartphones and communication apparatus",
    suggested_gst_rate: 18.0,
    entry_type: "GOODS",
    chapter: "Chapter 85",
    keywords: "mobile phone smartphone telecom",
    is_active: 1,
  },
  {
    code: "8708",
    description: "Parts and accessories of motor vehicles",
    suggested_gst_rate: 28.0,
    entry_type: "GOODS",
    chapter: "Chapter 87",
    keywords: "automobile spare parts vehicle accessories",
    is_active: 1,
  },
  {
    code: "9403",
    description: "Other furniture and parts thereof",
    suggested_gst_rate: 18.0,
    entry_type: "GOODS",
    chapter: "Chapter 94",
    keywords: "furniture table chair cabinet",
    is_active: 1,
  },
  {
    code: "9603",
    description: "Brooms, brushes and mops",
    suggested_gst_rate: 12.0,
    entry_type: "GOODS",
    chapter: "Chapter 96",
    keywords: "brush broom mop cleaning",
    is_active: 1,
  },
];

module.exports = {
  STARTER_HSN_SAC_MASTER,
};
